README.md, conf/application.conf
If set, `$ZK_HOSTS` will override the default value for `kafka-manager.zkhosts`.
=> Allow configuration of zk-hosts using env variable ZK_HOSTS

app/kafka/manager/KafkaManagerActor.scala, test/kafka/manager/utils/TestClusterConfig.scala
Curator assumes the default ZooKeeper port 2181 if none is specified, so
this validation check is unnecessary.
=> Remove unnecessary zkHosts validation

app/views/topic/topicList.scala.html
It wont compile, the error was:
/app/views/topic/topicList.scala.html:6: type TopicListWithMoreInfo is not a member of package kafka.manager
after checkingout, there is no such class, the expected class is TopicListExtended, and it compiles and works great this way. thanks.
=> Fix class name type TopicListWithMoreInfo -> TopicListExtended

src/templates/etc-default
This PR resolves following error
```
Play server process ID is 13339
Exception in thread "main" java.io.FileNotFoundException: /usr/share/kafka-manager/RUNNING_PID (Permission denied)
at java.io.FileOutputStream.open(Native Method)
at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
at play.core.server.NettyServer$$anonfun$createServer$1.apply(NettyServer.scala:242)
at play.core.server.NettyServer$$anonfun$createServer$1.apply(NettyServer.scala:230)
at scala.Option.map(Option.scala:146)
at play.core.server.NettyServer$.createServer(NettyServer.scala:230)
at play.core.server.NettyServer$$anonfun$main$3.apply(NettyServer.scala:289)
at play.core.server.NettyServer$$anonfun$main$3.apply(NettyServer.scala:284)
at …
```
=> Fixed RPM build

app/kafka/manager/BrokerViewCacheActor.scala, test/controller/api/TestKafkaHealthCheck.scala
Throwable cause instead of being passed as template argument, should be passed as first argument to log.error calls (see http://doc.akka.io/api/akka/current/index.html#akka.event.LoggingAdapter )
This bug is causing warnings like https://github.com/yahoo/kafka-manager/issues/67
=> Fixed logging of errors in BrokerViewCacheActor

app/assets/stylesheets/index.less, app/controllers/ReassignPartitions.scala, app/kafka/manager/ActorModel.scala, app/kafka/manager/BrokerViewCacheActor.scala, app/kafka/manager/ClusterManagerActor.scala, app/kafka/manager/KafkaJMX.scala, app/kafka/manager/KafkaManager.scala, app/kafka/manager/utils/Helpers.scala, app/views/common/expandedBrokerMetrics.scala.html, app/views/common/shortBrokerMetrics.scala.html, app/views/main.scala.html, app/views/topic/manualMultipleAssignments.scala.html, app/views/topic/topicList.scala.html, conf/routes, test/kafka/manager/TestClusterManagerActor.scala, test/kafka/manager/TestKafkaManagerActor.scala
Automatic random generation of partition assignments limits the user control over them. At times it is necessary, or at least desirable to tweak the assignment and manually make decisions on which replica of which partition goes to. An example of such a situation is when only a small subset of topics takes most of data flow on the cluster, and you may wanna make sure they are separated, in different brokers.
A new view was created for these decisions, where the user can see both the current assignment and some broker metrics to aid on choices. Two metrics were also added to this view: Process CPU Load and System CPU Load.
This view can be accessed through the route /clusters/:cluster/assignments/manual or by clicking the button "Manually Set Partition Assignmentns" in …
=> Manual partition assignment

app/assets/stylesheets/index.less, app/controllers/ReassignPartitions.scala, app/kafka/manager/ClusterManagerActor.scala
Addresses issue #75 . This patch makes KM not to generate reassignments when any of the selected topics is already undergoing reassignments. Also changed the border color to lighter red (indication that the topic is under reassignment).
=> add check for topics undergoing reassignment

sbt
Change sbt launcher download location to the Typesafe official repo and update the `curl` invocation to follow 3xx responses.
Fixes #103
=> Fix sbt download repo

app/views/topic/topicListContent.scala.html
Fix the problem of not being on warning/danger level on topic list when percentage is between 33 and 66.
=> Fix broker skew percentage and under-replicated warning level

app/controllers/ReassignPartitions.scala, app/kafka/manager/BrokerViewCacheActor.scala, app/kafka/manager/KafkaManager.scala, app/kafka/manager/KafkaStateActor.scala, app/views/main.scala.html, app/views/topic/manualAssignments.scala.html, build.sbt, test/kafka/manager/TestKafkaManagerActor.scala
Previously, if a broker any broker was down, the list of brokers in
manual partition assignments would get messed up, even if that broker
had no topics.
This is a rebased version of #119
=> Broker Down bugfix

build.sbt, conf/application.conf, conf/logger.xml, project/plugins.sbt, src/templates/etc-default
Hey there,
thank you for making kafka-manager! It's awesome. 
We deployed that into production last week and then the default configuration spilled our harddrive with log-files.
So I thought it would be good to alter the default configuration to be more logging friendly.
Things which I changed:
* Added a logger.xml file which is used by default now
* Make akka log through play's logging 
* Updating akka to 2.3.14 and include akka-slf4j for logging
* Configure some hopefully sane defaults for the logfile of kafka-manager (daily rotation, with max 5 files)
* Removed the sbt-coffeescript plugin, because coffeescript isnt used in this project
=> Add default logging for akka

app/kafka/manager/KafkaStateActor.scala
Currently offsets cache is started regardless of whether consumer information is displayed or not, which can result in RejectedExecutionException for big Kafka cluster. This PR enables KM not to start offsets cache and load empty partitions offsets map into the internal cache of OffsetsCache when consumer polling is disabled.
=> disable offsets cache when consumer polling is disabled

app/kafka/manager/BrokerViewCacheActor.scala, app/kafka/manager/ClusterManagerActor.scala, app/kafka/manager/KafkaJMX.scala
This significantly reduces time to calculate/display topics and brokers sizes.
=> calculate broker/topic sizes only once per update

build.sbt
See: https://github.com/webjars/dustjs-linkedin/issues/4
=> Bump dustjs-linkedin to avoid missing requirejs config warnings

app/controllers/Topic.scala, app/views/topic/topicDeleteConfirm.scala.html, app/views/topic/topicViewContent.scala.html, conf/routes
This attempts to resolve: https://github.com/yahoo/kafka-manager/issues/197
When you click on `Delete Topic` you are taken to a page like this:
This should stop accidental deletion of topics and adds very little extra code. Hitting `Delete Topic` on the new page takes the action of the old `Delete Topic` button
=> Add confirm page for kafka-manager topic delete

project/plugins.sbt
When I clone the kafka-manager repository and try to build it, sbt hangs at below step and give no more information, 
"[info] Loading project definition from /opt/Development/github_repo/kafka-manager/project"
Try to google it and found similar problem:
http://stackoverflow.com/questions/11373536/play-framework-hangs-on-startup-at-loading-project-definition-from
sbt wasn't truly hanging, it was just pulling a maven and downloading the Internet.
This pull request is to change the logging level from "Warn" to "Info" to give more information during the sbt build.
=> Output more information during "./sbt clean dist"

build.sbt
Add a workaround for hseeberger/scala-sbt#3 to build inside a docker container.
Otherwise results in the following error if building inside docker on aufs:
```
[info] Compiling 123 Scala sources and 2 Java sources to /root/kafka-manager/target/scala-2.11/classes...
[error] File name too long
[error] one error found
```
=> Add a workaround for hseeberger/scala-sbt#3 to build inside a docker container.

app/views/broker/brokerView.scala.html, app/views/topic/topicList.scala.html, app/views/topic/topicListContent.scala.html
It fixes the sorting bug in leader size column. Currently, the leader size column sorts things by numbers so 1TB comes before 2GB.
=> fix leader size sorting bug

build.sbt
Doing `sbt rpm:packageBin`It throws an error that build failed saying that rpmGroup is not set.
This solves the problem.
```
[error] error: Group field must be present in package: (main package)
[error] error: Package has no %description: kafka-manager-1.3.2.1-1.noarch
[info] Building target platforms: noarch-yahoo-Linux
java.lang.RuntimeException: Unable to run rpmbuild, check output for details. Errorcode 1
at scala.sys.package$.error(package.scala:27)
at com.typesafe.sbt.packager.rpm.RpmHelper$$anonfun$buildPackage$1.apply(RpmHelper.scala:86)
at com.typesafe.sbt.packager.rpm.RpmHelper$$anonfun$buildPackage$1.apply(RpmHelper.scala:71)
at sbt.IO$.withTemporaryDirectory(IO.scala:291)
at com.typesafe.sbt.packager.rpm.RpmHelper$.buildPackage(RpmHelper.scala:71)
at …
```
=> Adds rpm group

app/controllers/Logkafka.scala, app/controllers/Topic.scala, app/kafka/manager/actor/cluster/KafkaStateActor.scala, app/kafka/manager/model/model.scala, app/kafka/manager/utils/LogkafkaNewConfigs.scala, app/kafka/manager/utils/TopicConfigs.scala, test/kafka/manager/utils/TestClusterConfig.scala
I've added feature that was be able to select version 0.10.1.1, 0.10.2.0 and 0.10.2.1 from UI.
Tests are passing and the instance I'm running locally seems to be working properly.
And He is saying too. (See: #394)
Thank you.
=> Support kafka 0.10.x.x

app/kafka/manager/model/model.scala, test/kafka/manager/model/KafkaVersionTest.scala
#415 I supported sorting version of Kafka in selectbox. 
When you update/add a cluster, sorted version is displayed in the selectbox.
Thanks.
=> Support sorting version of Kafka in selectbox

README.md, app/controllers/Logkafka.scala, app/controllers/Topic.scala, app/kafka/manager/actor/cluster/KafkaStateActor.scala, app/kafka/manager/model/model.scala, app/kafka/manager/utils/LogkafkaNewConfigs.scala, app/kafka/manager/utils/TopicConfigs.scala, test/kafka/manager/model/KafkaVersionTest.scala, test/kafka/manager/utils/TestClusterConfig.scala
Adds config option for Kafka 0.11.0.0. No special handling of anything new, but it seems to run fine.
Fixes #422
=> Add config option for 0.11.0.0

app/kafka/manager/actor/cluster/KafkaStateActor.scala, app/kafka/manager/model/ActorModel.scala, test/kafka/manager/utils/TestCreateTopic.scala, test/kafka/manager/utils/TestReassignPartitions.scala
Use a separate thread to get the topic offsets
=> Use a separate thread to get the topic offsets to fixed bug 'Yikes! Ask timed out...'

app/controllers/Logkafka.scala, app/controllers/Topic.scala, app/kafka/manager/actor/cluster/KafkaStateActor.scala, app/kafka/manager/model/model.scala, app/kafka/manager/utils/LogkafkaNewConfigs.scala, app/kafka/manager/utils/TopicConfigs.scala, test/kafka/manager/model/KafkaVersionTest.scala, test/kafka/manager/utils/TestClusterConfig.scala
The newest versions, both which came out in November, 2017: https://kafka.apache.org/downloads
I don't know if there are other compatibility changes that need to be made, but https://github.com/yahoo/kafka-manager/issues/451 implies that probably not.
=> Add in 1.0.0 and 0.11.0.2 as valid versions

app/views/main.scala.html
The current container cause extra columns to fall outside table, especially in "Topics" screen. The container-fluid takes to whole screen and prevents from that.
=> Changed default container to fluid one, so that the view looks good on larger screens

conf/application.conf
Added `akka.logger-startup-timeout = 60s `property to the `application.conf` in order to deal with the following error which seems to be quite common:
```
[WARN] [03/27/2018 09:41:31.681] [main] [EventStream(akka://kafka-manager-system)] Logger log1-Slf4jLogger did not respond within Timeout(5000 milliseconds) to InitializeLogger(bus)
error while starting up loggers
akka.ConfigurationException: Logger specified in config can't be loaded [akka.event.slf4j.Slf4jLogger] due to [akka.event.Logging$LoggerInitializationException: Logger log1-Slf4jLogger did not respond with LoggerInitialized, sent instead [TIMEOUT]]
at akka.event.LoggingBus$$anonfun$4$$anonfun$apply$1.applyOrElse(Logging.scala:116)
at akka.event.LoggingBus$$anonfun$4$$anonfun$apply$1.applyOrElse(Logging.scala:115)
at …
```
=> Added akka.logger-startup-timeout property

app/views/cluster/clusterViewContent.scala.html
When operating Kafka-manager for multiple tenants, its not uncommon to remove the `KMClusterManagerFeature` feature in order to make Kafka-manager read-only and hide details about the setup. I'd suggest that this also includes the ZooKeeper-connect information. However, the ZooKeeper ensemble is _always_ displayed in the Cluster info, alongside the current Kafka version.
This PR removes the ZooKeeper-connect information when `KMClusterManagerFeature` is absent.
=> Remove zookeeper info when cluster-manager feature absent

app/models/navigation/Menus.scala
When features `KMPreferredReplicaElectionFeature` and `KMReassignPartitionsFeature` are removed, the menu navigation buttons for the corresponding features are visible but non-functional.
Let's remove these menu items when the features are absent.
=> Remove navigation menu items when features are absent

app/controllers/api/KafkaStateCheck.scala
Currently, the results can be returned in a random order, which makes the
per-partition stats less useful than they could be.
=> Sort topicSummary JSON by partition number

app/controllers/Logkafka.scala, app/controllers/Topic.scala, app/kafka/manager/actor/cluster/KafkaStateActor.scala, app/kafka/manager/model/model.scala, app/kafka/manager/utils/LogkafkaNewConfigs.scala, app/kafka/manager/utils/TopicConfigs.scala, test/controller/api/TestKafkaStateCheck.scala, test/kafka/manager/TestKafkaManager.scala, test/kafka/manager/TestKafkaManagerActor.scala, test/kafka/manager/model/KafkaVersionTest.scala, test/kafka/manager/utils/TestClusterConfig.scala
Doing the same thing as everything for `2.0.0`, just for `2.1.0` now. Seems it passes tests...
=> Add support for Kafka 2.1.0 and 2.1.1

app/kafka/manager/model/model.scala
as [ https://community.hortonworks.com/questions/85754/why-ambari-is-setting-the-security-protocol-of-the.html](url) say，
> Kafka security is developed by Hortonworks. Before it shipped into Apache Kafka we shipped it in HDP. At that time we called the SASL protocol as PLAINTEXTSASL which later changed SASL_PLAINTEXT.
Avoid key not found: PLAINTEXTSASL ERROR when kafka cluster set SASL protocol to PLAINTEXTSASL
=> Add "PLAINTEXTSASL" in model.scala to support HDP kafka

app/views/reassignPartitions.scala.html
For the `Request Data` section in the `/clusters/$CLUSTER_NAME/assignment` page, this change make it so it also sorts by the partition ID after sorting by topic:
We have it running on our staging env
---
=> Add Secondary Sort by partition ID for assignment view

README.md, app/controllers/BasicAuthenticationFilter.scala, conf/application.conf
This PR adds the capability to limit access to members of a defined LDAP or AD Group.
If the config key is empty, access is not limited.
=> Add Group Filter

.travis.yml, build.sbt
An update to `openjdk:8-jre-slim` earlier this year ( docker-library/openjdk#322 ) removed the `unzip` package in the base image, which the current generated dockerfile relies on. 
No associated issues were found, but ran into this while building a fresh docker image locally, and could prevent future updates from getting to the Docker Repo.
---
Since the Travis CI migration from [Trusty to Xenial](https://blog.travis-ci.com/2019-04-15-xenial-default-build-environment), oraljdk8 is no longer supported. Updating the travis jdk config to use `openjdk8` instead ([Travis CI issue thread](https://travis-ci.community/t/install-of-oracle-jdk8-is-failing/4365/3)).
=> Re-adding unzip to Docker via apt-get; changing Travis build to use OpenJDK8

app/controllers/BasicAuthenticationFilter.scala
=> Fix LDAP authentication does not support colons in password

app/controllers/PreferredReplicaElection.scala, app/features/ApplicationFeature.scala, app/kafka/manager/KafkaManager.scala, app/kafka/manager/actor/KafkaManagerActor.scala, app/kafka/manager/actor/cluster/ClusterManagerActor.scala, app/kafka/manager/model/ActorModel.scala, app/kafka/manager/utils/ZkUtils.scala, app/kafka/manager/utils/zero81/SchedulePreferredLeaderElectionCommand.scala, app/models/navigation/BreadCrumbs.scala, app/models/navigation/Menus.scala, app/models/navigation/QuickRoutes.scala, app/views/scheduleLeaderElection.scala.html, conf/application.conf, conf/routes, test/kafka/manager/TestKafkaManager.scala
We recently worked on adding a feature (new tab & REST APIs) to Kafka Manager which would allow users to schedule the replica leader election. We thought it might be helpful for other users as well so would like to share it here and preferably merge it upstream ([yahoo/kafka-manager](https://github.com/yahoo/kafka-manager)).
I am quite new to Scala/Akka so I would appreciate if you could let me know what changes you'd like to see in this patch and how it can be best used to improve Kafka Manager.
=> Feature for scheduling preferred replica leader election

README.md, app/controllers/BasicAuthenticationFilter.scala, conf/application.conf
Signed-off-by: Parth Kolekar <parthkolekar@indeed.com>
=> Create a new option to trust all non-expired certificates during LDAP authentication

app/kafka/manager/model/model.scala
from https://github.com/yahoo/CMAK/commit/08a03329607026dd09381af12b492a22ce264119 introduce PLAINTEXTSASL , but mistakenlly let it point to SASL_PLAINTEXT instead of PLAINTEXTSASL , which cause duplicate SASL_PLAINTEXT displayed in list and PLAINTEXTSASL  is also can't be really set.
=> cluster new/edit page duplicate security protocol SASL_PLAINTEXT fix

build.sbt
Building RPM on newer systems defaults RPM compression is ZSTD which prevents older systems from installing rpm
=> Set RPM compression to preserve backwards compatability

app/kafka/manager/model/ActorModel.scala, project/plugins.sbt
This will sort the list of topics a consumer is assigned to.
Two minor changes as well, change the repositories to https (removes the sbt warning about that) and some whitespace changes, which my editor is doing by default. If required I can revert those easily.
Thank you!
=> Sort topics in consumer view

app/kafka/manager/model/model.scala
CMAK currently does not support using OAUTHBEARER for the sasl.mechanism in the cluster configuration UI.  This PR adds that support.
=> Support OAUTHBEARER SASL mechanism
