yahoo/CMAK

app/kafka/manager/TopicIdentity.scala

java.lang.ArithmeticException: / by zero 
Defined to return 100% brokersSpreadPercentage in case of numBrokers is 0

Fix for #20

---

build.sbt
project/plugins.sbt

This is to address https://github.com/yahoo/kafka-manager/issues/18 .  While I'm not sure that's a productive route it's easy to implement.

adding build options for sbt-assembly.

---

app/controllers/ReassignPartitions.scala
app/kafka/manager/ActorModel.scala
app/kafka/manager/ClusterManagerActor.scala
app/kafka/manager/KafkaManager.scala
app/models/form/ReassignPartitionOperation.scala
app/views/topic/confirmAssignment.scala.html
app/views/topic/topicViewContent.scala.html
conf/application.conf
test/kafka/manager/TestClusterManagerActor.scala
test/kafka/manager/TestKafkaManager.scala

Enables selecting specific brokers for reassigning partitions.
Checks if the brokers in the assignments are valid.

reassign partitions to specific set of brokers

---

app/controllers/ReassignPartitions.scala
app/models/form/ReassignPartitionOperation.scala
app/views/topic/confirmAssignment.scala.html
app/views/topic/confirmMultipleAssignments.scala.html
app/views/topic/runMultipleAssignments.scala.html
app/views/topic/topicList.scala.html
conf/application.conf
conf/routes

Enables reassigning multiple topics at once.

reassign multiple topics

---

app/kafka/manager/KafkaManagerActor.scala

Update the cluster when JMX Polling changed.

Enable/disable JMX polling at runtime

---

app/assets/stylesheets/index.less
app/controllers/Topic.scala
app/kafka/manager/ActorModel.scala
app/kafka/manager/BrokerViewCacheActor.scala
app/kafka/manager/KafkaManager.scala
app/kafka/manager/TopicViewCacheActor.scala
app/views/topic/topicList.scala.html
app/views/topic/topicListContent.scala.html
conf/application.conf

Displays:
- Number of Partitions
- Number of Brokers
- Brokers Spread %

Display useful information on topic list page

---

app/kafka/manager/ActorModel.scala
app/kafka/manager/KafkaManager.scala
app/views/broker/brokerView.scala.html
app/views/broker/brokerViewContent.scala.html
app/views/topic/topicViewContent.scala.html

1) break word for partitions so it doesn't overflow broker view table
2) add DataTable plugin for broker view table
3) sort broker partitions and topics numerically/alphabetically

Some UI improvements

---

app/views/topic/manualAssignments.scala.html

I find it quite usefull to have colors to quickly see where my replica are, here is an example:

adding colors to manual assignments

---

app/controllers/Logkafka.scala
app/kafka/manager/ActorModel.scala
app/kafka/manager/ClusterManagerActor.scala
app/kafka/manager/KafkaManager.scala
app/kafka/manager/LogkafkaCommandActor.scala
app/kafka/manager/LogkafkaStateActor.scala
app/kafka/manager/LogkafkaViewCacheActor.scala
app/kafka/manager/utils/Logkafka.scala
app/kafka/manager/utils/LogkafkaAdminUtils.scala
app/kafka/manager/utils/LogkafkaZkUtils.scala
app/models/form/LogkafkaOperation.scala
app/models/navigation/BreadCrumbs.scala
app/views/logkafka/createLogkafka.scala.html
app/views/logkafka/logkafkaListContent.scala.html
app/views/logkafka/logkafkaView.scala.html
app/views/logkafka/logkafkaViewContent.scala.html
app/views/logkafka/updateConfig.scala.html
test/kafka/manager/TestClusterManagerActor.scala
test/kafka/manager/TestKafkaManager.scala
test/kafka/manager/TestKafkaManagerActor.scala
test/kafka/manager/TestLogkafkaStateActor.scala
test/kafka/manager/utils/TestCreateLogkafka.scala

I replace hostname with logkafka id, and changed a lot of files, I have checked it several times.
Added no new features.

logkafka: replace hostname with logkafka id

---

app/kafka/manager/utils/logkafka81/LogConfig.scala
app/kafka/manager/utils/logkafka82/LogConfig.scala
test/kafka/manager/utils/TestCreateLogkafka.scala

logkafka: add line_delimiter and remove_delimiter

---

app/kafka/manager/utils/AdminUtils.scala
test/kafka/manager/utils/TestCreateTopic.scala

Resolves https://github.com/yahoo/kafka-manager/issues/210

Kafka 0.9.x topic change notification fix

---

app/controllers/BasicAuthenticationFilter.scala
app/loader/KafkaManagerLoader.scala
conf/application.conf

added a very basic http authentication filter so that malicious user does not have un-authentication access to perform destructive operation like deleting a topic.
thanks to https://github.com/Kaliber/play-basic-authentication-filter for the filter

Add basic auth

---

README.md

Update version number of supported versions.

Documentation: Update for kafka 0.9.0.1

---

conf/logback.xml
conf/logger.xml

Also I added totalSizeCap = 5GB
For some reason current logger configuration didn't work for me. But with adding full path for rotation of logs started.

Fix log rollig

---

app/loader/KafkaManagerLoader.scala
app/models/navigation/Menus.scala
app/models/navigation/QuickRoutes.scala
app/views/navigation/clusterMenu.scala.html
conf/application.conf

Support HTTP context in URLs

---

app/controllers/ReassignPartitions.scala
app/controllers/Topic.scala
app/kafka/manager/KafkaManager.scala
app/kafka/manager/actor/KafkaManagerActor.scala
app/kafka/manager/actor/cluster/ClusterManagerActor.scala
app/kafka/manager/actor/cluster/KafkaCommandActor.scala
app/kafka/manager/actor/cluster/KafkaStateActor.scala
app/kafka/manager/model/ActorModel.scala
app/kafka/manager/model/model.scala
app/kafka/manager/model/package.scala
app/kafka/manager/utils/zero81/ReassignPartitionCommand.scala
app/models/form/ReassignPartitionOperation.scala
app/models/navigation/QuickRoutes.scala
app/views/topic/topicView.scala.html
app/views/topic/topicViewContent.scala.html
build.sbt
conf/application.conf
conf/consumer.properties
conf/routes
project/plugins.sbt
test/controller/api/TestKafkaStateCheck.scala
test/kafka/manager/TestBrokerViewCacheActor.scala
test/kafka/manager/TestClusterManagerActor.scala
test/kafka/manager/TestKafkaManager.scala
test/kafka/manager/TestKafkaManagerActor.scala
test/kafka/manager/TestKafkaStateActor.scala
test/kafka/manager/model/BrokerIdentityTest.scala
test/kafka/manager/utils/TestReassignPartitions.scala
test/kafka/test/KafkaTestBroker.scala
test/kafka/test/SeededBroker.scala

Add support for force assign and fixes to work with secured Kafka.

Force assign and security

---

app/controllers/api/KafkaStateCheck.scala
build.sbt
conf/routes
test/controller/api/TestKafkaStateCheck.scala

- Consumer API routes fix. 
- Extra lag information exposed.
- Tests adjusted.

consumer summary REST API - adding more information.

---

app/views/broker/brokerViewContent.scala.html
app/views/topic/topicListContent.scala.html
app/views/topic/topicViewContent.scala.html

This PR is inspired by #280. It would definitely help users understand metrics easily.

Added hints for helping user understand metrics meaning

---

app/controllers/api/KafkaStateCheck.scala
conf/routes

Signed-off-by: Stephen Gran <stephen.gran@piksel.com>

add an API query for an extended broker list view

---

app/kafka/manager/model/ActorModel.scala

Ignoring the offset values if the consumer offset count is -1.

Not considering the offset count for in-active partitions

---

app/controllers/ApiHealth.scala
app/loader/KafkaManagerLoader.scala
conf/application.conf
conf/routes

This fixes #150 and this fixes #322

added api health route, giving a 200

---

app/views/cluster/addCluster.scala.html

Checkbox was out of alignment, using the label field caused it to look wrong.

Fix checkbox alignment

---

test/kafka/manager/utils/TestClusterConfig.scala

I have added serialization/deserialization test for ver 0.10.0.0 to TestClusterConfig.
Thanks.

Add serialization/deserialization test for ver 0.10.0.0

---

test/kafka/manager/utils/TestClusterConfig.scala

I have added serialization/deserialization test for ver 0.10.1.0 to TestClusterConfig.
Thanks.

Add serialization/deserialization test for ver 0.10.1.0

---

test/kafka/manager/model/KafkaVersionTest.scala

I would like to contribute to the improvement of test coverage.
I added test case to KafkaVersionTest class.
Thanks.

Add test cases for KafkaVersion

---

README.md

I have updated Kafka version written in README.md requirement.
Thanks.

Updated Kafka version written in README.md requirement.

---

app/kafka/manager/utils/package.scala
app/views/consumer/consumedTopicViewContent.scala.html
app/views/topic/topicListContent.scala.html
app/views/topic/topicViewContent.scala.html

The suggested implementation for https://github.com/yahoo/kafka-manager/issues/446

Format offset values for readability

---

app/kafka/manager/model/ActorModel.scala
test/kafka/manager/model/BrokerIdentityTest.scala

Add check for listener_security_protocol_map

---

app/controllers/Logkafka.scala
app/controllers/Topic.scala
app/kafka/manager/actor/cluster/KafkaStateActor.scala
app/kafka/manager/model/ActorModel.scala
app/kafka/manager/model/model.scala
app/kafka/manager/utils/LogkafkaNewConfigs.scala
app/kafka/manager/utils/TopicConfigs.scala
app/kafka/manager/utils/zero90/GroupMetadataManager.scala
build.sbt
conf/consumer.properties
project/plugins.sbt
src/templates/etc-default
test/controller/api/TestKafkaStateCheck.scala
test/kafka/manager/TestKafkaManager.scala
test/kafka/manager/TestKafkaManagerActor.scala
test/kafka/manager/TestKafkaMetrics.scala
test/kafka/manager/model/KafkaVersionTest.scala
test/kafka/test/KafkaTestBroker.scala
test/kafka/test/SeededBroker.scala

This complement pull request https://github.com/yahoo/kafka-manager/pull/519 in order to have successful tests and to add 1.0.1 version added everywhere

Make all the test passing

---

app/controllers/Logkafka.scala
app/controllers/Topic.scala
app/kafka/manager/actor/cluster/KafkaStateActor.scala
app/kafka/manager/model/model.scala
app/kafka/manager/utils/LogkafkaNewConfigs.scala
app/kafka/manager/utils/TopicConfigs.scala
test/kafka/manager/TestKafkaMetrics.scala
test/kafka/manager/model/KafkaVersionTest.scala
test/kafka/manager/utils/TestClusterConfig.scala

Added support for kafka v1.1.1. 
All `sbt test` passed.

Add support for kafka v1.1.1

---

app/controllers/ApiHealth.scala
app/controllers/Application.scala
app/controllers/Cluster.scala
app/controllers/Consumer.scala
app/controllers/Logkafka.scala
app/controllers/PreferredReplicaElection.scala
app/controllers/ReassignPartitions.scala
app/controllers/Topic.scala
app/controllers/api/KafkaStateCheck.scala
app/controllers/package.scala

The Security vulnerabilities of Web Application Potentially Vulnerable to Clickjacking Scan By Nessus

Web Application Potentially Vulnerable to Clickjacking For Nessus

---

README.md
app/controllers/BasicAuthenticationFilter.scala
build.sbt
conf/application.conf

Update BasicAuthenticationFilter to work with Active Directory service

Basic authentication with ldap support

---

app/controllers/Logkafka.scala
app/controllers/Topic.scala
app/kafka/manager/actor/cluster/KafkaStateActor.scala
app/kafka/manager/model/model.scala
app/kafka/manager/utils/LogkafkaNewConfigs.scala
app/kafka/manager/utils/TopicConfigs.scala
test/controller/api/TestKafkaStateCheck.scala
test/kafka/manager/TestKafkaManager.scala
test/kafka/manager/TestKafkaManagerActor.scala
test/kafka/manager/model/KafkaVersionTest.scala
test/kafka/manager/utils/TestClusterConfig.scala

This adds support for Kafka 2.2.0 similar to previous PRs.

Support Kafka 2.2.0

---

app/views/cluster/addCluster.scala.html
app/views/cluster/updateCluster.scala.html

Improve "not recommended for large number of consumers" message

---

README.md

updated README to reflect name change

---

app/controllers/Logkafka.scala
app/controllers/Topic.scala
app/kafka/manager/actor/cluster/KafkaStateActor.scala
app/kafka/manager/model/model.scala
app/kafka/manager/utils/LogkafkaNewConfigs.scala
app/kafka/manager/utils/TopicConfigs.scala
test/controller/api/TestKafkaStateCheck.scala
test/kafka/manager/TestKafkaManager.scala
test/kafka/manager/TestKafkaManagerActor.scala
test/kafka/manager/model/KafkaVersionTest.scala
test/kafka/manager/utils/TestClusterConfig.scala

This adds support for Kafka 2.4.0 similar to previous PRs.

Add support Kafka 2.4.0

---

.travis.yml
README.md
app/kafka/manager/actor/cluster/KafkaStateActor.scala
app/kafka/manager/package.scala
app/kafka/manager/utils/logkafka81/LogConfig.scala
app/kafka/manager/utils/logkafka82/LogConfig.scala
app/kafka/manager/utils/zero10/LogConfig.scala
app/kafka/manager/utils/zero11/LogConfig.scala
app/kafka/manager/utils/zero81/LogConfig.scala
app/kafka/manager/utils/zero82/LogConfig.scala
app/kafka/manager/utils/zero90/LogConfig.scala
build.sbt
project/build.properties
sbt

Change to java 11, rename to cmak

---

build.sbt

fix(jquery): Upgrade Jquery version

---

app/controllers/Logkafka.scala
app/controllers/Topic.scala
app/kafka/manager/actor/cluster/KafkaStateActor.scala
app/kafka/manager/model/model.scala
app/kafka/manager/utils/LogkafkaNewConfigs.scala
app/kafka/manager/utils/TopicConfigs.scala
build.sbt
sbt
test/kafka/manager/TestKafkaManagerActor.scala
test/kafka/manager/model/KafkaVersionTest.scala
test/kafka/manager/utils/TestClusterConfig.scala

Added latest kafka versions (2.7.0, 2.8.0, 2.8.1, 3.0.0, 3.1.0)

Add latest kafka versions

---

screwdriver.yaml

create screwdriver build pipeline

---

README.md
app/controllers/BasicAuthenticationFilter.scala
conf/application.conf

Signed-off-by: Parth Kolekar <parthkolekar@indeed.com>

Implement LDAP + StartTLS in CMAK
